<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

namespace Protobuff\Person;

use UnexpectedValueException;

/**
 * Protobuf type <code>Protobuff.Person.EyeColour</code>
 */
class EyeColour
{
    /**
     * Generated from protobuf enum <code>UNKNOWN_EYE_COLOR = 0;</code>
     */
    const UNKNOWN_EYE_COLOR = 0;
    /**
     * Generated from protobuf enum <code>RED = 1;</code>
     */
    const RED = 1;
    /**
     * Generated from protobuf enum <code>BROWN = 2;</code>
     */
    const BROWN = 2;
    /**
     * Generated from protobuf enum <code>BLUE = 3;</code>
     */
    const BLUE = 3;

    private static $valueToName = [
        self::UNKNOWN_EYE_COLOR => 'UNKNOWN_EYE_COLOR',
        self::RED => 'RED',
        self::BROWN => 'BROWN',
        self::BLUE => 'BLUE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(EyeColour::class, \Protobuff\Person_EyeColour::class);

