<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: front.proto

namespace GPBMetadata;

class Front
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5c0a0b66726f6e742e70726f746f120f50726f746f627566662e66726f6e7422340a065469636b6574120d0a0570686f6e65180120012809120d0a056d6f64656c180220012809120c0a046e616d65180320012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

