<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

namespace Protobuff;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Protobuff.Person</code>
 */
class Person extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 age = 1;</code>
     */
    protected $age = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>bytes small_picture = 4;</code>
     */
    protected $small_picture = '';
    /**
     * Generated from protobuf field <code>bool is_profile_verified = 5;</code>
     */
    protected $is_profile_verified = false;
    /**
     *main
     *
     * Generated from protobuf field <code>float height = 6;</code>
     */
    protected $height = 0.0;
    /**
     * aaa
     *
     * Generated from protobuf field <code>repeated string phone_numbers = 7;</code>
     */
    private $phone_numbers;
    /**
     * Generated from protobuf field <code>repeated float tttt = 8;</code>
     */
    private $tttt;
    /**
     * Generated from protobuf field <code>.Protobuff.Person.EyeColour eye_color = 9;</code>
     */
    protected $eye_color = 0;
    /**
     * Generated from protobuf field <code>repeated .Protobuff.front.Ticket tickets = 10;</code>
     */
    private $tickets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $age
     *     @type string $name
     *     @type string $small_picture
     *     @type bool $is_profile_verified
     *     @type float $height
     *          main
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $phone_numbers
     *           aaa
     *     @type float[]|\Google\Protobuf\Internal\RepeatedField $tttt
     *     @type int $eye_color
     *     @type \Protobuff\Front\Ticket[]|\Google\Protobuf\Internal\RepeatedField $tickets
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Main::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 age = 1;</code>
     * @return int
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * Generated from protobuf field <code>int32 age = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->age = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes small_picture = 4;</code>
     * @return string
     */
    public function getSmallPicture()
    {
        return $this->small_picture;
    }

    /**
     * Generated from protobuf field <code>bytes small_picture = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSmallPicture($var)
    {
        GPBUtil::checkString($var, False);
        $this->small_picture = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_profile_verified = 5;</code>
     * @return bool
     */
    public function getIsProfileVerified()
    {
        return $this->is_profile_verified;
    }

    /**
     * Generated from protobuf field <code>bool is_profile_verified = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsProfileVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->is_profile_verified = $var;

        return $this;
    }

    /**
     *main
     *
     * Generated from protobuf field <code>float height = 6;</code>
     * @return float
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     *main
     *
     * Generated from protobuf field <code>float height = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkFloat($var);
        $this->height = $var;

        return $this;
    }

    /**
     * aaa
     *
     * Generated from protobuf field <code>repeated string phone_numbers = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPhoneNumbers()
    {
        return $this->phone_numbers;
    }

    /**
     * aaa
     *
     * Generated from protobuf field <code>repeated string phone_numbers = 7;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPhoneNumbers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->phone_numbers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated float tttt = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTttt()
    {
        return $this->tttt;
    }

    /**
     * Generated from protobuf field <code>repeated float tttt = 8;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTttt($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->tttt = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Protobuff.Person.EyeColour eye_color = 9;</code>
     * @return int
     */
    public function getEyeColor()
    {
        return $this->eye_color;
    }

    /**
     * Generated from protobuf field <code>.Protobuff.Person.EyeColour eye_color = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setEyeColor($var)
    {
        GPBUtil::checkEnum($var, \Protobuff\Person_EyeColour::class);
        $this->eye_color = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Protobuff.front.Ticket tickets = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTickets()
    {
        return $this->tickets;
    }

    /**
     * Generated from protobuf field <code>repeated .Protobuff.front.Ticket tickets = 10;</code>
     * @param \Protobuff\Front\Ticket[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTickets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protobuff\Front\Ticket::class);
        $this->tickets = $arr;

        return $this;
    }

}

