<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

namespace Protobuff;

if (false) {
    /**
     * This class is deprecated. Use Protobuff\Person\EyeColour instead.
     * @deprecated
     */
    class Person_EyeColour {}
}
class_exists(Person\EyeColour::class);
@trigger_error('Protobuff\Person_EyeColour is deprecated and will be removed in the next major release. Use Protobuff\Person\EyeColour instead', E_USER_DEPRECATED);

